export const BATTING_STAT_IDS = {
  HITS: 8,
  AT_BATS: 6,
  RUNS: 7,
  SINGLES: 9,
  DOUBLES: 10,
  TRIPLES: 11,
  HOME_RUNS: 12,
  RBI: 13,
  STOLEN_BASES: 16,
  WALKS: 18,
  HIT_BY_PITCH: 20,
} as const;

export const BATTING_STAT_LABELS = {
  [BATTING_STAT_IDS.HITS]: 'H',
  [BATTING_STAT_IDS.AT_BATS]: 'AB',
  [BATTING_STAT_IDS.RUNS]: 'R',
  [BATTING_STAT_IDS.SINGLES]: '1B',
  [BATTING_STAT_IDS.DOUBLES]: '2B',
  [BATTING_STAT_IDS.TRIPLES]: '3B',
  [BATTING_STAT_IDS.HOME_RUNS]: 'HR',
  [BATTING_STAT_IDS.RBI]: 'RBI',
  [BATTING_STAT_IDS.STOLEN_BASES]: 'SB',
  [BATTING_STAT_IDS.WALKS]: 'BB',
  [BATTING_STAT_IDS.HIT_BY_PITCH]: 'HBP',
} as const;

export const PITCHING_STAT_IDS = {
  INNINGS_PITCHED: 50,
  WHIP: 27,
  ERA: 26,
  WINS: 28,
  SAVES: 32,
  OUTS: 33,
  HITS_ALLOWED: 34,
  EARNED_RUNS: 37,
  WALKS_ALLOWED: 39,
  HIT_BY_PITCH_ALLOWED: 41,
  STRIKEOUTS: 42,
  BLOWN_SAVES: 84,
} as const;

export const PITCHING_STAT_LABELS = {
  [PITCHING_STAT_IDS.INNINGS_PITCHED]: 'IP',
  [PITCHING_STAT_IDS.WHIP]: 'WHIP',
  [PITCHING_STAT_IDS.ERA]: 'ERA',
  [PITCHING_STAT_IDS.WINS]: 'W',
  [PITCHING_STAT_IDS.SAVES]: 'SV',
  [PITCHING_STAT_IDS.OUTS]: 'OUT',
  [PITCHING_STAT_IDS.HITS_ALLOWED]: 'H',
  [PITCHING_STAT_IDS.EARNED_RUNS]: 'ER',
  [PITCHING_STAT_IDS.WALKS_ALLOWED]: 'BB',
  [PITCHING_STAT_IDS.HIT_BY_PITCH_ALLOWED]: 'HBP',
  [PITCHING_STAT_IDS.STRIKEOUTS]: 'K',
  [PITCHING_STAT_IDS.BLOWN_SAVES]: 'BS',
} as const;

// Filter Types - matches the PlayerFilterType in types/hooks.ts
export const FILTER_TYPES = {
  ALL_BATTERS: 'ALL_BATTERS',
  ALL_PITCHERS: 'ALL_PITCHERS',
  C: 'C',
  FIRST_BASE: '1B',
  SECOND_BASE: '2B',
  SHORTSTOP: 'SS',
  THIRD_BASE: '3B',
  OUTFIELD: 'OF',
  UTIL: 'Util',
  STARTING_PITCHER: 'SP',
  RELIEF_PITCHER: 'RP',
} as const;

// Filter Display Names
export const FILTER_LABELS = {
  [FILTER_TYPES.ALL_BATTERS]: 'All Batters',
  [FILTER_TYPES.ALL_PITCHERS]: 'All Pitchers',
  [FILTER_TYPES.C]: 'C',
  [FILTER_TYPES.FIRST_BASE]: '1B',
  [FILTER_TYPES.SECOND_BASE]: '2B',
  [FILTER_TYPES.SHORTSTOP]: 'SS',
  [FILTER_TYPES.THIRD_BASE]: '3B',
  [FILTER_TYPES.OUTFIELD]: 'OF',
  [FILTER_TYPES.UTIL]: 'Util',
  [FILTER_TYPES.STARTING_PITCHER]: 'SP',
  [FILTER_TYPES.RELIEF_PITCHER]: 'RP',
} as const;

// Filter Button Configuration - Grouped by Player Type
export const BATTER_FILTER_BUTTONS = [
  { value: FILTER_TYPES.ALL_BATTERS, label: FILTER_LABELS[FILTER_TYPES.ALL_BATTERS] },
  { value: FILTER_TYPES.C, label: FILTER_LABELS[FILTER_TYPES.C] },
  { value: FILTER_TYPES.FIRST_BASE, label: FILTER_LABELS[FILTER_TYPES.FIRST_BASE] },
  { value: FILTER_TYPES.SECOND_BASE, label: FILTER_LABELS[FILTER_TYPES.SECOND_BASE] },
  { value: FILTER_TYPES.SHORTSTOP, label: FILTER_LABELS[FILTER_TYPES.SHORTSTOP] },
  { value: FILTER_TYPES.THIRD_BASE, label: FILTER_LABELS[FILTER_TYPES.THIRD_BASE] },
  { value: FILTER_TYPES.OUTFIELD, label: FILTER_LABELS[FILTER_TYPES.OUTFIELD] },
  { value: FILTER_TYPES.UTIL, label: FILTER_LABELS[FILTER_TYPES.UTIL] },
] as const;

export const PITCHER_FILTER_BUTTONS = [
  { value: FILTER_TYPES.ALL_PITCHERS, label: FILTER_LABELS[FILTER_TYPES.ALL_PITCHERS] },
  { value: FILTER_TYPES.STARTING_PITCHER, label: FILTER_LABELS[FILTER_TYPES.STARTING_PITCHER] },
  { value: FILTER_TYPES.RELIEF_PITCHER, label: FILTER_LABELS[FILTER_TYPES.RELIEF_PITCHER] },
] as const;

// Backward compatibility - all filters combined
export const FILTER_BUTTONS = [
  ...BATTER_FILTER_BUTTONS,
  ...PITCHER_FILTER_BUTTONS,
] as const; 