export const BATTING_STAT_IDS = {
  HITS: 8,
  AT_BATS: 6,
  RUNS: 7,
  SINGLES: 10,
  DOUBLES: 11,
  TRIPLES: 12,
  HOME_RUNS: 13,
  RBI: 9,
  STOLEN_BASES: 16,
  WALKS: 15,
  HIT_BY_PITCH: 18,
} as const;

export const BATTING_STAT_LABELS = {
  [BATTING_STAT_IDS.HITS]: 'H',
  [BATTING_STAT_IDS.AT_BATS]: 'AB',
  [BATTING_STAT_IDS.RUNS]: 'R',
  [BATTING_STAT_IDS.SINGLES]: '1B',
  [BATTING_STAT_IDS.DOUBLES]: '2B',
  [BATTING_STAT_IDS.TRIPLES]: '3B',
  [BATTING_STAT_IDS.HOME_RUNS]: 'HR',
  [BATTING_STAT_IDS.RBI]: 'RBI',
  [BATTING_STAT_IDS.STOLEN_BASES]: 'SB',
  [BATTING_STAT_IDS.WALKS]: 'BB',
  [BATTING_STAT_IDS.HIT_BY_PITCH]: 'HBP',
} as const; 